---
abstract: 'The great new JCOM::BM!'
author:
  - 'Jerome Eteve <jerome.eteve@gmail.com>'
build_requires:
  DBIx::Class: 0
  DBIx::Class::Schema::Loader: 0
  Module::Pluggable::Object: 0
  Moose: 0
  Test::Fatal: 0.008
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: JCOM-BM
provides:
  JCOM::BM:
    file: lib/JCOM/BM.pm
    version: 0.01
  JCOM::BM::DBICFactory:
    file: lib/JCOM/BM/DBICFactory.pm
    version: 0
  JCOM::BM::DBICObject:
    file: lib/JCOM/BM/DBICObject.pm
    version: 0
  JCOM::BM::DBICWrapper:
    file: lib/JCOM/BM/DBICWrapper.pm
    version: 0
  JCOM::BM::Factory:
    file: lib/JCOM/BM/Factory.pm
    version: 0
  JCOM::KVPairs:
    file: lib/JCOM/KVPairs.pm
    version: 0
  JCOM::KVPairs::DBICRs:
    file: lib/JCOM/KVPairs/DBICRs.pm
    version: 0
  JCOM::KVPairs::Pure:
    file: lib/JCOM/KVPairs/Pure.pm
    version: 0
  JCOM::Sequence:
    file: lib/JCOM/Sequence.pm
    version: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
